services:
  
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
      MYSQL_USER_NAME: ${MYSQL_USER_NAME}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
      
  nginx:
    build: requirements/nginx
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    ports:
      - "9000:9000"
    environment:
      MYSQL_HOST:  ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR: ${WP_DATABASE_USR}
      WP_DATABASE_PWD: ${WP_DATABASE_PWD}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USR: ${WP_ADMIN_USR}
      WP_ADMIN_PWD: ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER_USR: ${WP_USER_USR}
      WP_USER_PWD: ${WP_USER_PWD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/faaraujo/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/faaraujo/data/mariadb

networks:
  inception:
    driver: bridge